spring.application.name=compiladores-refact-spring
server.port=8080

spring.jackson.serialization.indent-output=true

logging.level.com.umg=INFO
logging.level.org.springframework.web=INFO

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Swagger / OpenAPI
springdoc.swagger-ui.path=/api/compiler/docs
springdoc.api-docs.path=/api/compiler/openapi
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.packages-to-scan=com.umg.api.compiler
springdoc.paths-to-match=/api/compiler/**
