package com.umg.model.dialect;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class KeywordRegistry {

    private static final Set<String> COMMON_KEYWORDS = new HashSet<>(Arrays.asList(
        "SELECT", "FROM", "WHERE", "INSERT", "INTO", "VALUES", "UPDATE", "SET",
        "DELETE", "CREATE", "TABLE", "ALTER", "DROP", "TRUNCATE",
        "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "OUTER", "CROSS", "ON",
        "GROUP", "BY", "ORDER", "HAVING", "UNION", "ALL",
        "WITH", "AS", "DISTINCT", "LIMIT", "OFFSET", "TOP",
        "AND", "OR", "NOT", "IN", "LIKE", "BETWEEN", "IS", "NULL",
        "CASE", "WHEN", "THEN", "ELSE", "END",
        "PRIMARY", "KEY", "FOREIGN", "REFERENCES",
        "CONSTRAINT", "DEFAULT", "CHECK", "UNIQUE",
        "DATABASE", "SCHEMA", "INDEX", "VIEW",
        "ASC", "DESC",
        "ADD", "COLUMN", "MODIFY",
        "INT", "INTEGER", "VARCHAR", "CHAR", "BOOLEAN", "BOOL",
        "FLOAT", "DOUBLE", "DECIMAL", "NUMERIC", "TEXT", "BLOB",
        "DATE", "TIME", "TIMESTAMP", "DATETIME",
        "NO", "ACTION", "CASCADE", "SET", "RESTRICT",
        "EXISTS", "IF", "REPLACE", "TEMPORARY", "TEMP",
        "BEFORE", "AFTER", "EACH", "ROW", "STATEMENT",
        "BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT",
        "GRANT", "REVOKE", "DENY",
        "PROCEDURE", "FUNCTION", "TRIGGER", "SEQUENCE",
        "EXEC", "EXECUTE", "CALL", "RETURN", "DECLARE",
        "PRINT", "RAISERROR",
        "MERGE", "USING", "MATCHED",
        "ANY", "SOME", "TRUE", "FALSE",
        "SERIAL", "BIGINT", "SMALLINT", "TINYINT", "BYTEA",
        "ENUM", "SET",
        "CHARACTER", "VARYING",
        "PRECISION", "UNSIGNED", "SIGNED",
        "ZEROFILL", "AUTO_INCREMENT", "CURRENT_TIMESTAMP",
        "ON", "UPDATE", "CURRENT_DATE", "CURRENT_TIME"
    ));

    private static final Set<String> MYSQL_KEYWORDS = new HashSet<>(Arrays.asList(
        "AUTO_INCREMENT", "ENGINE", "CHARSET", "COLLATE", "CHARACTER",
        "INNODB", "MYISAM", "MEMORY",
        "SHOW", "DESCRIBE", "EXPLAIN",
        "MATCH", "AGAINST", "BOOLEAN", "MODE",
        "PARTITION", "PARTITIONS",
        "DELAYED", "HIGH_PRIORITY", "LOW_PRIORITY",
        "STRAIGHT_JOIN", "SQL_SMALL_RESULT", "SQL_BIG_RESULT",
        "SQL_BUFFER_RESULT", "SQL_CACHE", "SQL_NO_CACHE",
        "IGNORE", "STRAIGHT_JOIN",
        "DUPLICATE", "KEY",
        "ROW_FORMAT", "DYNAMIC", "COMPRESSED", "REDUNDANT", "COMPACT",
        "PACK_KEYS", "MIN_ROWS", "MAX_ROWS",
        "AVG_ROW_LENGTH", "DATA_DIRECTORY", "INDEX_DIRECTORY",
        "TABLESPACE", "STORAGE", "DISK", "MEMORY",
        "EXTENT_SIZE", "INITIAL_SIZE", "NODEGROUP",
        "UNDO", "UNDEFINED", "OFF",
        "ALGORITHM", "COPY", "INPLACE", "INSTANT",
        "LOCK", "SHARED", "EXCLUSIVE", "NONE",
        "ENABLE", "DISABLE", "KEYS",
        "DISCARD", "IMPORT", "TABLESPACE",
        "ORDER", "BY",
        "FORCE", "USE", "INDEX",
        "CHANGE", "FIRST", "AFTER",
        "RENAME", "TO",
        "MAXVALUE", "MINVALUE", "CYCLE", "INCREMENT", "START", "CACHE",
        "ROLE", "ADMIN", "USER",
        "IDENTIFIED", "BY", "PASSWORD",
        "HOST", "PROXY",
        "FLUSH", "PRIVILEGES",
        "OPTIMIZE", "ANALYZE", "CHECK", "REPAIR",
        "QUICK", "EXTENDED",
        "RESET", "PURGE", "BINARY",
        "WRAPPER", "LANGUAGE", "SQL",
        "DEFINER", "INVOKER", "SECURITY",
        "TERMINATED", "ENCLOSED", "ESCAPED",
        "LINES", "STARTING",
        "INFILE", "OUTFILE", "LOAD", "DATA",
        "INTO", "FIELDS",
        "DUMPFILE",
        "SONAME", "AGGREGATE",
        "RETURNS", "TYPE",
        "CONTINUE", "HANDLER", "EXIT",
        "UNDO", "CONDITION",
        "FETCH", "CLOSE", "OPEN",
        "GOTO", "LABEL",
        "LEAVE", "ITERATE", "REPEAT", "LOOP",
        "WHILE", "LEAVE", "ITERATE",
        "SQLWARNING", "NOTFOUND", "SQLEXCEPTION",
        "RESIGNAL", "SIGNAL",
        "DIAGNOSTICS",
        "GET", "STACKED"
    ));

    private static final Set<String> POSTGRESQL_KEYWORDS = new HashSet<>(Arrays.asList(
        "ANALYSE", "ANALYZE",
        "ASC", "DESC",
        "BETWEEN", "BIGINT",
        "BOOLEAN",
        "CASCADE",
        "CHECK",
        "COLLATE",
        "COLUMN",
        "CONSTRAINT",
        "CONVERT",
        "CROSS",
        "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",
        "CURSOR",
        "DEALLOCATE",
        "DEC",
        "DECIMAL",
        "DEFERRABLE",
        "DESC",
        "DISTINCT",
        "DO",
        "DOMAIN",
        "DOUBLE",
        "DROP",
        "EACH",
        "ELSE",
        "END",
        "EXCEPT",
        "EXCLUDING",
        "EXISTS",
        "EXTRACT",
        "FALSE",
        "FETCH",
        "FLOAT",
        "FOR",
        "FOREIGN",
        "FREEZE",
        "FULL",
        "FUNCTION",
        "GLOBAL",
        "GRANT",
        "GROUP",
        "HAVING",
        "IDENTITY",
        "ILIKE",
        "IMMEDIATE",
        "IN",
        "INDEX",
        "INHERITS",
        "INITIALLY",
        "INNER",
        "INOUT",
        "INPUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INTEGER",
        "INTERSECT",
        "INTERVAL",
        "INTO",
        "IS",
        "ISNULL",
        "JOIN",
        "LATERAL",
        "LEADING",
        "LEFT",
        "LIKE",
        "LIMIT",
        "LISTEN",
        "LOAD",
        "LOCAL",
        "LOCALTIME", "LOCALTIMESTAMP",
        "MATERIALIZED",
        "NATURAL",
        "NCHAR",
        "NEW",
        "NONE",
        "NOT",
        "NOTHING",
        "NOTIFY",
        "NOTNULL",
        "NULL",
        "NULLIF",
        "NUMERIC",
        "OF",
        "OFF",
        "OFFSET",
        "OIDS",
        "OLD",
        "ON",
        "ONLY",
        "OPERATOR",
        "OR",
        "ORDER",
        "OUT",
        "OUTER",
        "OVER",
        "OVERLAPS",
        "OVERLAY",
        "OWNED",
        "OWNER",
        "PARTIAL",
        "PARTITION",
        "PASSING",
        "PLACING",
        "PLANS",
        "POLICY",
        "POSITION",
        "PRECISION",
        "PREPARE",
        "PREPARED",
        "PRESERVE",
        "PRIMARY",
        "PRIOR",
        "PRIVILEGES",
        "PROCEDURAL",
        "PROCEDURE",
        "PUBLICATION",
        "QUOTE",
        "RANGE",
        "READ",
        "REAL",
        "REASSIGN",
        "RECHECK",
        "RECURSIVE",
        "REF",
        "REFERENCES",
        "REFERENCING",
        "REINDEX",
        "RELATIVE",
        "RELEASE",
        "RENAME",
        "REPEATABLE",
        "REPLACE",
        "REPLICA",
        "RESET",
        "RESTART",
        "RESTRICT",
        "RETURNING",
        "REVOKE",
        "RIGHT",
        "ROLE",
        "ROLLBACK",
        "ROW",
        "ROWS",
        "RULE",
        "SAVEPOINT",
        "SCHEMA",
        "SCROLL",
        "SEARCH",
        "SECURITY",
        "SELECT",
        "SEQUENCE",
        "SEQUENCES",
        "SERIALIZABLE",
        "SESSION",
        "SESSION_USER",
        "SET",
        "SETOF",
        "SHARE",
        "SHOW",
        "SIMILAR",
        "SIMPLE",
        "SMALLINT",
        "SNAPSHOT",
        "SOME",
        "SQL",
        "STANDALONE",
        "START",
        "STATEMENT",
        "STATISTICS",
        "STORAGE",
        "STRICT",
        "STRIP",
        "SUBSCRIPTION",
        "SUBSTRING",
        "SYMMETRIC",
        "SYSID",
        "SYSTEM",
        "TABLE",
        "TABLES",
        "TABLESAMPLE",
        "TABLESPACE",
        "TEMP",
        "TEMPORARY",
        "TEXT",
        "THEN",
        "TIME",
        "TIMESTAMP",
        "TO",
        "TRAILING",
        "TRANSACTION",
        "TREAT",
        "TRIGGER",
        "TRIM",
        "TRUE",
        "TRUNCATE",
        "TRUSTED",
        "TYPE",
        "UNBOUNDED",
        "UNCOMMITTED",
        "UNENCRYPTED",
        "UNION",
        "UNIQUE",
        "UNKNOWN",
        "UNLISTEN",
        "UNLOGGED",
        "UNTIL",
        "UPDATE",
        "USER",
        "USING",
        "VACUUM",
        "VALID",
        "VALIDATE",
        "VALIDATOR",
        "VALUE",
        "VALUES",
        "VARCHAR",
        "VARIADIC",
        "VARYING",
        "VERBOSE",
        "VERSION",
        "VIEW",
        "VIEWS",
        "VOLATILE",
        "WHEN",
        "WHERE",
        "WHITESPACE",
        "WINDOW",
        "WITH",
        "WITHIN",
        "WITHOUT",
        "WORK",
        "WRAPPER",
        "WRITE",
        "XML",
        "XMLATTRIBUTES",
        "XMLCONCAT",
        "XMLELEMENT",
        "XMLEXISTS",
        "XMLFOREST",
        "XMLNAMESPACES",
        "XMLPARSE",
        "XMLPI",
        "XMLROOT",
        "XMLSERIALIZE",
        "XMLTABLE",
        "YEAR",
        "YES",
        "ZONE"
    ));

    private static final Set<String> SQL_SERVER_KEYWORDS = new HashSet<>(Arrays.asList(
        "ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC",
        "AUTHORIZATION", "BACKUP", "BEGIN", "BETWEEN", "BREAK",
        "BROWSE", "BULK", "BY", "CASCADE", "CASE", "CHECK",
        "CHECKPOINT", "CLOSE", "CLUSTERED", "COALESCE", "COLLATE",
        "COLUMN", "COMMIT", "COMPUTE", "CONSTRAINT", "CONTAINS",
        "CONTAINSTABLE", "CONTINUE", "CONVERT", "CREATE", "CROSS",
        "CURRENT", "CURRENT_DATE", "CURRENT_TIME",
        "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR",
        "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT",
        "DELETE", "DENY", "DESC", "DISK", "DISTINCT",
        "DISTRIBUTED", "DOUBLE", "DROP", "DUMP", "ELSE", "END",
        "ERRLVL", "ESCAPE", "EXCEPT", "EXEC", "EXECUTE",
        "EXISTS", "EXIT", "EXTERNAL", "FETCH", "FILE",
        "FILLFACTOR", "FOR", "FOREIGN", "FREETEXT",
        "FREETEXTTABLE", "FROM", "FULL", "FUNCTION", "GOTO",
        "GRANT", "GROUP", "HAVING", "HOLDLOCK", "IDENTITY",
        "IDENTITYCOL", "IDENTITY_INSERT", "IF", "IN",
        "INDEX", "INNER", "INSERT", "INTERSECT", "INTO",
        "IS", "JOIN", "KEY", "KILL", "LEFT", "LIKE",
        "LINENO", "LOAD", "MERGE", "NATIONAL", "NOCHECK",
        "NONCLUSTERED", "NOT", "NULL", "NULLIF", "OF",
        "OFF", "OFFSET", " OFF", "ON", "OPEN",
        "OPENDATASOURCE", "OPENQUERY", "OPENROWSET",
        "OPENXML", "OPTION", "OR", "ORDER", "OUTER",
        "OVER", "PERCENT", "PIVOT", "PLAN", "PRECISION",
        "PRIMARY", "PRINT", "PROC", "PROCEDURE", "PUBLIC",
        "RAISERROR", "READ", "READTEXT", "RECONFIGURE",
        "REFERENCES", "REPLICATION", "RESTORE", "RESTRICT",
        "RETURN", "REVERT", "REVOKE", "RIGHT", "ROLLBACK",
        "ROWCOUNT", "ROWGUIDCOL", "ROW", "ROWS",
        "RULE", "SAVE", "SCHEMA", "SCHEMA", "SELECT",
        "SESSION_USER", "SET", "SETUSER", "SHUTDOWN",
        "SOME", "STATISTICS", "SYSTEM_USER", "TABLE",
        "TABLESAMPLE", "TEXTSIZE", "THEN", "TO", "TOP",
        "TRAN", "TRANSACTION", "TRIGGER", "TRUNCATE",
        "TSEQUAL", "UNION", "UNIQUE", "UNPIVOT", "UPDATE",
        "UPDATETEXT", "USE", "USER", "VALUES", "VARYING",
        "VIEW", "WAITFOR", "WHEN", "WHERE", "WHILE",
        "WITH", "WITHIN", "WRITETEXT",
        "NOCOUNT", "ROWCOUNT", "XACT_ABORT",
        "ARITHABORT", "ARITHIGNORE", "QUOTED_IDENTIFIER",
        "ANSI_NULLS", "ANSI_PADDING", "ANSI_WARNINGS",
        "CONCAT_NULL_YIELDS_NULL", "CURSOR_CLOSE_ON_COMMIT",
        "IMPLICIT_TRANSACTIONS", "NUMERIC_ROUNDABORT",
        "DATEFIRST", "DATEFORMAT",
        "TEXTSIZE", "LANGUAGE",
        "FORMATMESSAGE", "TRY", "CATCH", "THROW",
        "IIF", "CHOOSE",
        "COMPRESS", "DECOMPRESS",
        "STRING_AGG", "STRING_ESCAPE", "TRANSLATE",
        "SESSION", "PROCID",
        "FILENAME", "FILEGROUP", "FILEGROWTH", "FILEGROUP",
        "LOG", "SIZE", "MAXSIZE", "UNLIMITED", "FILEGROWTH",
        "NAME", "FILENAME",
        "ATTACH", "ATTACH_REBUILD_LOG",
        "EVENTDATA",
        "APPLOCK_MODE", "APPLOCK_TEST", "APP_NAME",
        "ASSEMBLYPROPERTY",
        "COL_LENGTH", "COL_NAME", "COLUMNPROPERTY",
        "OBJECT_NAME", "OBJECT_ID", "OBJECT_SCHEMA_NAME",
        "SQL_VARIANT_PROPERTY",
        "SERVERPROPERTY", "DATABASEPROPERTYEX",
        "INDEXKEY_PROPERTY", "INDEXPROPERTY", "INDEX_COL",
        "FULLTEXTCATALOGPROPERTY", "FULLTEXTSERVICEPROPERTY",
        "FILE_ID", "FILE_IDEX", "FILE_NAME", "FILEGROUP_ID",
        "FILEGROUP_NAME", "FILEGROUPPROPERTY",
        "FN_GET_SQL", "FN_HELPCOLLATIONS",
        "HOST_NAME", "HOST_ID",
        "IDENT_CURRENT", "IDENT_INCR", "IDENT_SEED",
        "PARSENAME", "PERMISSIONS",
        "SCHEMA_ID", "SCHEMA_NAME",
        "SCOPE_IDENTITY",
        "SERVERPROPERTY",
        "STATS_DATE",
        "TYPE_ID", "TYPE_NAME", "TYPEPROPERTY"
    ));

    public static boolean isCommonKeyword(String word) {
        return COMMON_KEYWORDS.contains(word.toUpperCase());
    }

    public static boolean isMySqlKeyword(String word) {
        return MYSQL_KEYWORDS.contains(word.toUpperCase());
    }

    public static boolean isPostgreSqlKeyword(String word) {
        return POSTGRESQL_KEYWORDS.contains(word.toUpperCase());
    }

    public static boolean isSqlServerKeyword(String word) {
        return SQL_SERVER_KEYWORDS.contains(word.toUpperCase());
    }

    public static boolean isKeywordForDialect(String word, SqlDialect dialect) {
        String upper = word.toUpperCase();
        if (COMMON_KEYWORDS.contains(upper)) return true;
        return switch (dialect) {
            case MYSQL -> MYSQL_KEYWORDS.contains(upper);
            case POSTGRESQL -> POSTGRESQL_KEYWORDS.contains(upper);
            case SQL_SERVER -> SQL_SERVER_KEYWORDS.contains(upper);
            default -> false;
        };
    }

    public static boolean isKeyword(String word) {
        String upper = word.toUpperCase();
        return COMMON_KEYWORDS.contains(upper)
            || MYSQL_KEYWORDS.contains(upper)
            || POSTGRESQL_KEYWORDS.contains(upper)
            || SQL_SERVER_KEYWORDS.contains(upper);
    }
}
