/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.view;
import com.umg.model.ViewModel;
import com.umg.controller.ViewController;
/**
 *
 * @author keyor
 */
public class Visa_Compilador extends javax.swing.JFrame {

    /**
     * Creates new form Visa_Compilador
     */
    public Visa_Compilador() {
        initComponents();
        ViewModel model = new ViewModel(this);
        ViewController controller = new ViewController(model);
        setController(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxAConsultas = new javax.swing.JTextArea();
        BtnAnalizar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnAyuda = new javax.swing.JButton();
        JPanel = new javax.swing.JPanel();
        DataBases = new javax.swing.JComboBox<>();
        BtnConsola = new javax.swing.JButton();
        BtnTokens = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnRegesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 73, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxAConsultas.setColumns(20);
        TxAConsultas.setRows(5);
        jScrollPane1.setViewportView(TxAConsultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, 160));

        BtnAnalizar.setBackground(new java.awt.Color(127, 243, 234));
        BtnAnalizar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnAnalizar.setText("Analizar");
        BtnAnalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAnalizar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnAnalizar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnAnalizar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        BtnLimpiar.setBackground(new java.awt.Color(139, 255, 165));
        BtnLimpiar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnLimpiar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnLimpiar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 30));

        BtnAyuda.setBackground(new java.awt.Color(252, 60, 129));
        BtnAyuda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnAyuda.setText("Ayuda");
        BtnAyuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAyuda.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnAyuda.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnAyuda.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        JPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 820, 420));

        DataBases.setBackground(new java.awt.Color(255, 123, 68));
        DataBases.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        DataBases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DataBase", "Offline", "Postgres", "SQL Server", "MaríaDB" }));
        jPanel1.add(DataBases, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        BtnConsola.setBackground(new java.awt.Color(67, 73, 80));
        BtnConsola.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnConsola.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsola.setText("Consola");
        BtnConsola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        BtnConsola.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnConsola.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnConsola.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        BtnTokens.setBackground(new java.awt.Color(67, 73, 80));
        BtnTokens.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnTokens.setForeground(new java.awt.Color(255, 255, 255));
        BtnTokens.setText("Tokens");
        BtnTokens.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        BtnTokens.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnTokens.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnTokens.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SQL QUERY");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        BtnRegesar.setBackground(new java.awt.Color(67, 73, 80));
        BtnRegesar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        BtnRegesar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegesar.setText("Regresar");
        BtnRegesar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 255, 0)));
        BtnRegesar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnRegesar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnRegesar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnRegesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 720, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visa_Compilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAnalizar;
    public javax.swing.JButton BtnAyuda;
    public javax.swing.JButton BtnConsola;
    public javax.swing.JButton BtnLimpiar;
    public javax.swing.JButton BtnRegesar;
    public javax.swing.JButton BtnTokens;
    public javax.swing.JComboBox<String> DataBases;
    public javax.swing.JPanel JPanel;
    public javax.swing.JTextArea TxAConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void setController(ViewController controller) {
        this.BtnAnalizar.addActionListener(controller);
        this.BtnAyuda.addActionListener(controller);
        this.BtnConsola.addActionListener(controller);
        this.BtnLimpiar.addActionListener(controller);
        this.BtnRegesar.addActionListener(controller);
        this.BtnTokens.addActionListener(controller);
        this.addWindowListener(controller);
    }
}
