/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.view;
import com.umg.model.ViewModel;
import com.umg.controller.ViewController;
/**
 *
 * @author keyor
 */
public class Visa_Compilador extends javax.swing.JFrame {

    /**
     * Creates new form Visa_Compilador
     */
    public Visa_Compilador() {
        initComponents();

        resultArea = new javax.swing.JTextArea();
        resultArea.setEditable(false);
        resultArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        resultArea.setBackground(new java.awt.Color(240, 240, 240));
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(resultArea);
        JPanel.setLayout(new java.awt.BorderLayout());
        JPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        initConnectionComponents();

        ViewModel model = new ViewModel(this);
        ViewController controller = new ViewController(model);
        setController(controller);
    }

    private void initConnectionComponents() {
        javax.swing.JLabel lblConexion = new javax.swing.JLabel("CONEXION BD");
        lblConexion.setFont(new java.awt.Font("Arial Black", 1, 14));
        lblConexion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        javax.swing.JLabel lblHost = new javax.swing.JLabel("Host:");
        lblHost.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 20));
        txtHost = new javax.swing.JTextField("localhost");
        txtHost.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel1.add(txtHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 47, 140, -1));

        javax.swing.JLabel lblPuerto = new javax.swing.JLabel("Puerto:");
        lblPuerto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 20));
        txtPuerto = new javax.swing.JTextField("3306");
        txtPuerto.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(txtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 77, 140, -1));

        javax.swing.JLabel lblBD = new javax.swing.JLabel("BD:");
        lblBD.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 20));
        txtBaseDatos = new javax.swing.JTextField();
        txtBaseDatos.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel1.add(txtBaseDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 107, 140, -1));

        javax.swing.JLabel lblUser = new javax.swing.JLabel("User:");
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, 20));
        txtUsuario = new javax.swing.JTextField("root");
        txtUsuario.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 137, 140, -1));

        javax.swing.JLabel lblPass = new javax.swing.JLabel("Pass:");
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, 20));
        txtPassword = new javax.swing.JPasswordField();
        txtPassword.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 167, 140, -1));

        BtnConectar = new javax.swing.JButton();
        BtnConectar.setText("Conectar");
        BtnConectar.setBackground(new java.awt.Color(100, 200, 255));
        BtnConectar.setFont(new java.awt.Font("Arial Black", 1, 12));
        jPanel1.add(BtnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 100, 30));

        lblEstadoConexion = new javax.swing.JLabel("Desconectado");
        lblEstadoConexion.setForeground(new java.awt.Color(255, 100, 100));
        lblEstadoConexion.setFont(new java.awt.Font("Arial", 1, 11));
        jPanel1.add(lblEstadoConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 205, -1, -1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxAConsultas = new javax.swing.JTextArea();
        BtnAnalizar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnAyuda = new javax.swing.JButton();
        JPanel = new javax.swing.JPanel();
        DataBases = new javax.swing.JComboBox<>();
        BtnConsola = new javax.swing.JButton();
        BtnTokens = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnRegesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 73, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxAConsultas.setColumns(20);
        TxAConsultas.setRows(5);
        jScrollPane1.setViewportView(TxAConsultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, 160));

        BtnAnalizar.setBackground(new java.awt.Color(127, 243, 234));
        BtnAnalizar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnAnalizar.setText("Analizar");
        BtnAnalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAnalizar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnAnalizar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnAnalizar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        BtnLimpiar.setBackground(new java.awt.Color(139, 255, 165));
        BtnLimpiar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnLimpiar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnLimpiar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 30));

        BtnAyuda.setBackground(new java.awt.Color(252, 60, 129));
        BtnAyuda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnAyuda.setText("Ayuda");
        BtnAyuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAyuda.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnAyuda.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnAyuda.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        JPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 820, 420));

        DataBases.setBackground(new java.awt.Color(255, 123, 68));
        DataBases.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        DataBases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DataBase", "Offline", "MySQL", "Postgres", "SQL Server", "MaríaDB" }));
        jPanel1.add(DataBases, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        BtnConsola.setBackground(new java.awt.Color(67, 73, 80));
        BtnConsola.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnConsola.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsola.setText("Consola");
        BtnConsola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        BtnConsola.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnConsola.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnConsola.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        BtnTokens.setBackground(new java.awt.Color(67, 73, 80));
        BtnTokens.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnTokens.setForeground(new java.awt.Color(255, 255, 255));
        BtnTokens.setText("Tokens");
        BtnTokens.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        BtnTokens.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnTokens.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnTokens.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SQL QUERY");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 153)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        BtnRegesar.setBackground(new java.awt.Color(67, 73, 80));
        BtnRegesar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        BtnRegesar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegesar.setText("Regresar");
        BtnRegesar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 255, 0)));
        BtnRegesar.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnRegesar.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnRegesar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(BtnRegesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 720, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visa_Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visa_Compilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAnalizar;
    public javax.swing.JButton BtnAyuda;
    public javax.swing.JButton BtnConsola;
    public javax.swing.JButton BtnLimpiar;
    public javax.swing.JButton BtnRegesar;
    public javax.swing.JButton BtnTokens;
    public javax.swing.JComboBox<String> DataBases;
    public javax.swing.JPanel JPanel;
    public javax.swing.JTextArea TxAConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextArea resultArea;
    public javax.swing.JTextField txtHost;
    public javax.swing.JTextField txtPuerto;
    public javax.swing.JTextField txtBaseDatos;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JButton BtnConectar;
    public javax.swing.JLabel lblEstadoConexion;

    public void setController(ViewController controller) {
        this.BtnAnalizar.addActionListener(controller);
        this.BtnAyuda.addActionListener(controller);
        this.BtnConsola.addActionListener(controller);
        this.BtnLimpiar.addActionListener(controller);
        this.BtnRegesar.addActionListener(controller);
        this.BtnTokens.addActionListener(controller);
        this.BtnConectar.addActionListener(controller);
        this.addWindowListener(controller);
    }
}
